version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for Analytics Service (Composer)
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for Notification Service (Composer)
  - package-ecosystem: "composer"
    directory: "/notification"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain Docker images in backend
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Maintain Docker images in frontend
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Maintain Docker images in notification
  - package-ecosystem: "docker"
    directory: "/notification"
    schedule:
      interval: "weekly"
