<?php

return [
    'ai_adapter' => env('SUPPORT_AI_ADAPTER', 'disabled'),
    'bff_shared_secret' => env('SUPPORT_BFF_SHARED_SECRET', ''),
    'generation_queue' => env('SUPPORT_GENERATION_QUEUE', 'ai-generation'),
    'indexing_queue' => env('SUPPORT_INDEXING_QUEUE', 'ai-indexing'),
    'question_character_limit' => 4000,
    'question_token_limit' => 2000,
    'evidence_token_limit' => 4000,
    'answer_token_limit' => 1000,
    'generation_reservation_tokens' => 6000,
    'user_rate_per_minute' => 10,
    'workspace_rate_per_minute' => 60,
    'active_per_user' => 2,
    'active_per_workspace' => 5,
    'workspace_daily_token_budget' => (int) env('SUPPORT_WORKSPACE_DAILY_TOKEN_BUDGET', 200000),
    'environment_daily_token_budget' => (int) env('SUPPORT_ENVIRONMENT_DAILY_TOKEN_BUDGET', 1000000),
    'indexing_daily_token_budget' => (int) env('SUPPORT_INDEXING_DAILY_TOKEN_BUDGET', 500000),
    'queue_deadline_seconds' => 30,
    'generation_deadline_seconds' => 90,
    'lease_seconds' => 30,
    'retention_days' => (int) env('SUPPORT_RETENTION_DAYS', 7),
    'deletion_grace_hours' => 24,
    'retrieval' => [
        'candidate_limit' => 30,
        'context_limit' => 6,
        'rrf_k' => 60,
        'minimum_score' => (float) env('SUPPORT_MINIMUM_RRF_SCORE', 0.025),
        'minimum_hybrid_vector_score' => (float) env('SUPPORT_MINIMUM_HYBRID_VECTOR_SCORE', 0.65),
        'minimum_semantic_vector_score' => (float) env('SUPPORT_MINIMUM_SEMANTIC_VECTOR_SCORE', 0.70),
        'profile' => env('SUPPORT_RETRIEVAL_PROFILE', 'hybrid-rrf-v2'),
        'prompt_version' => env('SUPPORT_PROMPT_VERSION', 'support-google-v1'),
    ],
    'google' => [
        'api_key' => env('GEMMA_API_KEY', ''),
        'chat_model' => env('SUPPORT_GOOGLE_CHAT_MODEL', 'gemma-4-26b-a4b-it'),
        'embedding_model' => env('SUPPORT_GOOGLE_EMBEDDING_MODEL', 'gemini-embedding-2'),
        'embedding_dimensions' => (int) env('SUPPORT_GOOGLE_EMBEDDING_DIMENSIONS', 768),
        'thinking_level' => env('SUPPORT_GOOGLE_THINKING_LEVEL', 'minimal'),
        'temperature' => (float) env('SUPPORT_GOOGLE_TEMPERATURE', 0.1),
        'timeout_seconds' => (int) env('SUPPORT_GOOGLE_TIMEOUT_SECONDS', 85),
    ],
];
